# Generated by Django 5.1.3 on 2024-12-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_advideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advideo',
            options={'managed': False},
        ),
    ]
