# Generated by Django 5.1.3 on 2024-12-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_alter_advideo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='remaining_guesses',
            field=models.IntegerField(default=5),
        ),
    ]
