# Generated by Django 5.1.1 on 2024-11-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_combo_ten_combo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ve',
            name='gia_ve',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='loai_ghe',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='ghe_ngoi',
        ),
        migrations.AddField(
            model_name='ve',
            name='combo',
            field=models.ManyToManyField(blank=True, to='database.combo'),
        ),
        migrations.AddField(
            model_name='ve',
            name='ghe_ngoi',
            field=models.ManyToManyField(to='database.ghengoi'),
        ),
    ]
